#!/usr/bin/env bash
set -e

# -------------------------
# ZSH INSTALL
# -------------------------
log() { echo "$*"; }

log "Installing zsh..."
sudo apt-get install -y zsh

# -------------------------
# OH MY ZSH
# -------------------------
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    log "Installing Oh My Zsh..."
    RUNZSH=no CHSH=no sh -c \
        "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    log "Oh My Zsh already installed, skipping."
fi

ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

# -------------------------
# PLUGINS
# -------------------------
declare -A PLUGINS=(
    ["zsh-autosuggestions"]="https://github.com/zsh-users/zsh-autosuggestions"
    ["zsh-syntax-highlighting"]="https://github.com/zsh-users/zsh-syntax-highlighting"
)

for name in "${!PLUGINS[@]}"; do
    target="$ZSH_CUSTOM/plugins/$name"
    if [[ ! -d "$target" ]]; then
        log "Installing plugin: $name"
        git clone --depth=1 "${PLUGINS[$name]}" "$target"
    else
        log "Plugin $name already present, skipping."
    fi
done

# -------------------------
# SET ZSH AS DEFAULT SHELL
# -------------------------
if [[ "$SHELL" != "$(which zsh)" ]]; then
    log "Setting zsh as default shell..."
    chsh -s "$(which zsh)"
fi

log "ZSH setup complete."
